# Generated by Django 2.2.9 on 2021-03-22 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about')),
                ('title1', models.CharField(max_length=200)),
                ('description1', models.TextField()),
                ('title2', models.CharField(max_length=200)),
                ('description2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='about')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('status', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Spices', 'Spices'), ('Eggs', 'Eggs'), ('Perfumes', 'Perfumes'), ('Neckless', 'Neckless'), ('Beads', 'Beads'), ('Earings', 'Earings')], max_length=15)),
                ('label', models.CharField(choices=[('S', 'secondary'), ('P', 'primary'), ('D', 'danger'), ('I', 'info')], max_length=2)),
                ('description', models.TextField()),
                ('img', models.ImageField(default='default.jpg', upload_to='static/images')),
                ('users_wishlist', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Payment received'), (3, 'Order being picked'), (4, 'Complete')], default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='slider')),
                ('heading', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='item')),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Electronics', 'Electronics'), ('Fruits', 'Fruits'), ('Detergents', 'Detergents'), ('Spices', 'Spices'), ('Eggs', 'Eggs'), ('Perfumes', 'Perfumes'), ('Neckless', 'Neckless'), ('Beads', 'Beads'), ('Earings', 'Earings')], default='Food', max_length=15)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('review', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Item picked'), (4, 'Shipped'), (5, 'Cancelled')], default=1)),
                ('last_updated', models.DateField(auto_now=True)),
                ('dated_added', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('delivered_at', models.CharField(max_length=255)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='addition_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='Food')),
                ('img', models.ImageField(upload_to='addition_info')),
                ('descriptions', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
            ],
        ),
    ]
