# Generated by Django 2.2.9 on 2021-03-20 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20210314_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
