# Generated by Django 2.2.9 on 2021-03-21 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='items',
        ),
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.ManyToManyField(to='catalog.OrderItem'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
