# Generated by Django 2.2.9 on 2021-03-21 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20210321_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='items',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
